version: '3'

services:
  db:
    image: postgres:14
    container_name: server-monitoring-db-dev
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  db-store:
